#!/usr/bin/env bash

CAKE_VERSION=${CAKE_VERSION:-"__PLEASE_PIN_A_CAKE_VERSION_HERE__"}
CAKE_IMAGE=${CAKE_IMAGE:-"visciang/cake:$CAKE_VERSION"}

if [ "$(uname)" == "Darwin" ]; then
    SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock"
fi

if [ "$CI" == "true" ]; then
    TI=""
else
    TI="-ti"
fi

docker run --init --rm $TI --network=host \
    -v /var/run/docker.sock:/var/run/docker.sock -v "$PWD:$PWD" -w "$PWD" \
    -e SSH_AUTH_SOCK="$SSH_AUTH_SOCK" -v "$SSH_AUTH_SOCK:$SSH_AUTH_SOCK" \
    -e LOG_LEVEL="${LOG_LEVEL:-notice}" \
    $CAKE_IMAGE "$@"
