on:
  push:
    tags: ['*']
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Version
        id: cake_version
        run: |
          case $GITHUB_REF in
            refs/tags/v*)    export CAKE_VERSION=${GITHUB_REF#refs/tags/v} ;;
            *)               export CAKE_VERSION=0.0.0 ;;
          esac

          echo "version=$CAKE_VERSION" >> $GITHUB_OUTPUT

      - name: Build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64 #,linux/arm64
          context: .
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CAKE_VERSION=${{ steps.cake_version.outputs.version }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cake:${{ steps.cake_version.outputs.version }}
          target: cake.app

      - name: cake building cake
        run: CAKE_VERSION=${{ steps.cake_version.outputs.version }} priv/cake run --verbose all
