on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build --file Dockerfile.bootstrap --target dake.app --tag dake:latest .
