on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Version
        id: dake_version
        run: |
          case $GITHUB_REF in
            refs/heads/main) export DAKE_VERSION=latest ;;
            refs/tags/v*) export DAKE_VERSION=${GITHUB_REF#refs/tags/v} ;;
            *) export DAKE_VERSION=development ;;
          esac

          echo "##[set-output name=version;]$DAKE_VERSION"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64 #,linux/arm64
          context: .
          file: ./Dockerfile.bootstrap
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dake:${{ steps.dake_version.outputs.version }}
          target: dake.app
